### ISSUE TITLE
Z position update for all imported TEM points

### ISSUE THREAD

**Issue by JaeEYang** [wright-cemrc-projects/corr#16]
The imported points on the FLM map all have correct Z positions based on the registered TEM map after the affine transformation. However, the imported TEM points are still lacking the Z position. Just simply update their Z based on the DrawnID(looking for the correct TEM MapID) to update the Z please. Should be an easy and fast fix

**Comment by larsonmattr** [comment]
The behavior of the program for updating Z positions of imported points is described in the wiki (https://github.com/wright-cemrc-projects/corr/wiki/When-are-points-transformed%3F)
