### ISSUE TITLE
Autoscale labels and indicators based on zoom/resolution.

### ISSUE THREAD

**Issue by wright-cemrc-projects** [wright-cemrc-projects/corr#25]
It's requested that we scale text labels appropriately based on the image resolution, so if two different resolution images are opened in the viewers we can still read the crosshairs and text labels regardless.

Additionally, it would be good to appropriately scale the labels as you zoom in on the images.

This feature/fix will be developed in branch `scaling-labels` and then merged into master when it is tested.

**Comment by larsonmattr** [comment]
Resolved with 7b5957bfaa7191c8ea02e27ee750768d81f21ea5
